name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - zlib=1.2.*
  - yaml=0.2.*
  - xz=5.2.*
  - urllib3=2.*
  - typing_extensions
  - sympy
  - sqlite
  - setuptools
  - scipy
  - scikit-learn
  - requests
  - pyyaml
  - python=3.8
  - pysocks
  - pooch
  - pip
  - pillow
  - openssl
  - openjpeg
  - numpy
  - networkx
  - mpmath
  - mpir
  - mpfr
  - mpc
  - mkl
  - markupsafe
  - lz4-c
  - libwebp-base
  - libuv
  - libtiff
  - libpng
  - libjpeg-turbo
  - libffi
  - libdeflate
  - lerc
  - lcms2
  - jpeg
  - joblib
  - jinja2
  - intel-openmp
  - idna
  - gmpy2
  - freetype
  - filelock
  - cudatoolkit=10.2
  - ca-certificates
  - brotli-python
