version: '3'
services:
  ryugu-gs:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/home/developer/Ryugu-GS
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP:ja
      - LC_ALL=ja_JP.UTF-8
    tty: true